aws/amazon-ecs-ami

Makefile
m1 (arm) macs return `arm64` from `uname -m`, rather than the linux standard of always returning `aarch64`
tested `make al2` on an m1 mac
NA
=> makefile fixup for m1 (arm) macos

al2.pkr.hcl, scripts/install-ecs-init.sh, variables.pkr.hcl
This variable allows users to specify their own al2 ecs-init install URL, to use instead of the standard path of:
```
"https://s3.$REGION.amazonaws.com${host_suffix}/amazon-ecs-agent-$REGION/ecs-init-$AGENT_VERSION-$INIT_REV.$AL_NAME.$ARCH.rpm"
```
The main purpose of this change is to enable us to build AMIs using alpha builds of the ecs-init package, so that we can test and qualify ecs-init working and running inside of an AMI.
Enhancement - Added support for building with a user-specified ecs-init URL
=> Add variable to specify url to install ecs-init from

al1.pkr.hcl, scripts/al1/configure-docker-storage-setup.sh
the docker-storage-setup binary sets up docker to use the devicemapper
storage driver. It expects a device named /dev/xvdcz to be present so
this device must be in the launch block device mappings in order for
this binary to run.
Internal functional test suite run on all AMIs with this change.
Bugfix - Fix AL1 recipe block device mapping and devicemapper docker-storage setup
=> Fix AL1 block device and docker storage setup

scripts/enable-ecs-agent-gpu-support.sh
There are issues with the `cuda-drivers-fabricmanager` package that can cause errors when trying to `yum update`. This cr updates the nvidia packages we're installing to remove this package and use current required ones.
Built ami with the changes in my own AWS account. Ran GPU functional tests with this ami. Tested on g4dn.2xlarge, p3.2xlarge, and p4d.24xlarge instances. 
New tests cover the changes: n/a
nvidia package install change to fix issue when running a yum update
=> nvidia package install change to fix issue when running a yum update

scripts/cleanup.sh
- the [[ -f ... ]] and [[ -d ... ]] checks are changed to use 'sudo test
-f and sudo test -d'. This is so that we correctly detect files that
are only readable by the root user.
- the cleanup script was leaving behind /root/.ssh/authorized_keys
because it was not using 'sudo' to check for this file
- the cleanup script was previously also leaving behind
/etc/sudoers.d/90-cloud-init-users, but we need this file for the
ec2-user to have sudo access, so delete it from the list of files to
delete from the AMI.
Created an AMI with this recipe, checked that build succeeds and `/root/.aws/authorized_keys` is deleted.
bugfix - delete /root/.aws/authorized_keys file on AMI build
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Cleanup script fix

scripts/enable-ecs-agent-inferentia-support.sh
this fixes an issue installing the neuron dkms package.
updated the script to reflect the instructions provided by the neuron
team in their public docs.
al2inf AMI was built and tested that neuron device was present and available
Bug - Fix bug in inferentia/neuron AMI package installation
=> Fix neuron install process

scripts/enable-ecs-agent-inferentia-support.sh
The neuron dkms packages have an issue with yum where they will remove
themselves after a package upgrade.
Anytime the neuron packages are upgraded they are liable to break any
customer who runs a "yum update" on the inferentia AMI.
This change deletes the neuron repo from yum, thereby disabling neuron
package upgrades on the inferentia AMI.
Built and run functional testing suite
bugfix: inferentia AMI: disable broken neuron package upgrades [#27](https://github.com/aws/amazon-ecs-ami/pull/27)
=> Delete neuron repo from inf AMI

al1.pkr.hcl, al2.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl
AMIs with different ids can have the same name. When this is the case, packer will fail with: `amazon-ebs.al2: Your query returned more than one result. Please try a more specific search, or set most_recent to true.`
This PR fixes that by using `most_recent = true` config.
Setting `most_recent = true` for [source_ami_filter](https://www.packer.io/plugins/builders/amazon/ebs#source_ami_filter) in all AL flavors.
`make static-check`
New tests cover the changes: yes 
* Enhancement - Set `most_recent = true` for `source_ami_filter` in order to avoid packer failures when duplicated AMIs exist.
=> Add most_recent = true to source_ami_filter for all al flavors

al2022.pkr.hcl, scripts/al2022/setup-motd.sh
AL2022 uses pam-motd. This disables their banner (30-banner) and adds a new banner (31-banner) containing the ECS motd.
see http://www.linux-pam.org/Linux-PAM-html/sag-pam_motd.html for pam-motd docs
Tested AMI build, verified that ECS 2022 motd displays as expected:
```
% ssh ec2-user@XXX.XXX.XXX.XXX
__|  __|  __|
_|  (   \__ \   Amazon Linux 2022 (ECS Optimized)
____|\___|____/   Preview
For documentation, visit http://aws.amazon.com/documentation/ecs
```
NA
=> Disable Amazon Linux 2022 motd, add ECS motd

scripts/al2022/install-workarounds.sh, variables.pkr.hcl
Changes in this PR contains
* Update `scripts/al2022/install-workarounds.sh` to get the latest release server. See the AL2022 version locking [here](https://docs.aws.amazon.com/linux/al2022/ug/version-locking.html).
* Install `amazon-ec2-net-utils` and `acpid` packages
* scripts/al2022/install-workarounds.sh - get the latest releaseserver from `dnf check-release-update`
* variables.pkr.hcl - add `amazon-ec2-net-utils` and `acpid` to al2022
* Built an AL2022 AMI, launched an EC2 instance, registered it to an ECS cluster, and ran a nginx task on the cluster successfully.
* Verified `amazon-ec2-net-utils` and `acpid` are installed on the container instance.
```
$ sudo dnf list installed | grep "ec2-net-utils"
amazon-ec2-net-utils.noarch            2.0.0-1.amzn2022                 @System …
```
=> [AL2022] Refactor ECS optimized AL2022 AMI building scripts - Part 2

scripts/install-exec-dependencies.sh, variables.pkr.hcl
Updating exec SSM Agent version to 3.1.1260.0 and sha sums for the binaries.
Passed relevant function tests for AL1, 2, 2022
Update exec ssm agent version to 3.1.1260.0 and the sha256 checksums
=> update exec ssm agent version to 3.1.1260.0 and the sha256 checksums

al2022.pkr.hcl
Fixed `AL_NAME` variable for AL2022 build script so that it pulls the correct build of init rpm.
Ran `make al2022`, verified that the init url is correct, and the build was successful
```
==> amazon-ebs.al2022: + ECS_INIT_URL=https://s3.us-west-2.amazonaws.com/amazon-ecs-agent-us-west-2/ecs-init-1.61.0-1.amzn2022.x86_64.rpm
```
New tests cover the changes: no 
=> Fixed AL_NAME for AL2022 scripts

scripts/enable-ecs-agent-gpu-support.sh
This PR adds ```nvidia-driver-latest-dkms``` package to the GPU installation script. This fixes errors faced due to Nvidia packages when updating kernel on old AMIs.
Created an AMI with old kernel (4.14.268) and ran ```yum update kernel``` command
Add nvidia-driver-latest-dkms package
=> Add nvidia-driver-latest-dkms package

generate-release-vars.sh
fixing variable `ami_name_x86` -> `ami_name_al2_x86` in generate-release-vars.sh
fixing variable `ami_name_x86` -> `ami_name_al2_x86` in generate-release-vars.sh
=> fixing variable `ami_name_al2_x86`  in generate-release-vars.sh

.gitignore, Makefile, al2022.pkr.hcl, al2022neu.pkr.hcl, scripts/al2022/install-neuron-packages.sh, scripts/enable-ecs-agent-inferentia-support.sh, scripts/install-additional-packages.sh
This PR adds a new build target - `al2022neu`, and adds `scripts/enable-ecs-agent-inferentia-support.sh` to AL2022 recipes.
* Add new target to Makefile
* Modify `al2022.pkr.hcl` build sources to include `al2022neu`, as well as two provisioners to
* run `scripts/enable-ecs-agent-inferentia-support.sh` to install neuron packages on AL2022 base instance and enable `INF` on instance.
* install necessary neuron packages that is not in AL2022 Repo yet in `install-neuron-packages.sh` (missed packages can be found in `scripts/al2022/install-neuron-packages.sh`). Downloaded AL2 version of those rpms and put them under `amazon-ecs-ami/additional-packages/al2022`
* Create `al2022neu.pkr.hcl` and `scripts/al2022/install-neuron-packages.sh`
* Modify `scripts/enable-ecs-agent-inferentia-support.sh` to …
=> Recipe Changes for AL2022 Neuron Support

al2022.pkr.hcl
Add a reboot before installing neuron packages for AL2022. Add a 60s wait for reboot.
For AL2022, since base AMI and distribution release version can be different for our AMI build process, there can potentially be a kernel update when we run `sudo dnf update -y --releasever=2022.0.20220831`. However, kernel update will not be installed without a reboot. Therefore, `uname -r` value which is used by `enable-ecs-agent-inferentia-support` script, will not be updated. When launching a new instance the kernel update will be installed, causing the neuron driver installed by `enable-ecs-agent-inferentia-support` script to not work, due to `neuron.ko` is installed in the legacy kernel version's directory.
Example:
```
sudo insmod /lib/modules/$(uname -r)/extra/neuron.ko
insmod: ERROR: could not …
```
=> Reboot AMI builder worker instance to install kernel update before installing neuron packages for AL2022

scripts/install-exec-dependencies.sh, variables.pkr.hcl
* Update SSM Agent binary version used for exec to ```3.1.1732.0```
* Update sha256 checksums
Made custom AMIs with the this change and verified all Exec checks pass
New tests cover the changes:  No new checks
Update to Exec SSM Agent version 3.1.1732.0
=> Update to Exec SSM Agent version 3.1.1732.0

.github/workflows/gitsecrets.yml
This PR adds a workaround for git secret scan failure, example - https://github.com/aws/amazon-ecs-ami/pull/84.
This is the same workaround as used in `amazon-ecs-agent` repo - https://github.com/aws/amazon-ecs-agent/pull/3442
=> fix PR git-secret scan workflow

al2.pkr.hcl, scripts/install-docker.sh, scripts/install-service-connect-appnet.sh
This PR includes changes to 
1. Install Appnet agent required during AMI build for al2. Appnet Agent rpm is not available for al2022 yet.
2. Disable userland-proxy for docker to avoid using up host ephemeral ports when client and server are colocated on host for SC bridge mode.
Tested the changes manually by building a new AMI and confirmed that
1. Agent successfully loaded the Appnet tarball for the expected filepath
2. `userland-proxy` config disabled in /etc/docker/daemon.json
3.  Was able to run SC task in bridge mode successfully and see that Appnet agent and Appnet relay containers were running.
=> Install Appnet Agent from AL repo; disable userland-proxy for docker

scripts/enable-ecs-agent-inferentia-support.sh
Previously when we upgrade to neuron v2 we removed `oci-add-hooks`. This needs to be added back. However, this package seems cause compatibility issue on AL2022 after IMDS v2 is enabled. To keep inferentia/neuron image and GPU image the same, adding this back to AL2 first and after we root cause the issue and resolve it we add it to AL2022 Neuron image.
Update `enable-ecs-agent-inferentia-support.sh` script.
Test AMI successfully built (in ci-prod account):
inf: ami-09d49f099bf4807ba
neu(with oci-add-hooks package): ami-0c6d60295213e8058
neu(without oci-add-hooks package): ami-02f9c3162bf307a0f
Run functional test (MACIS) on 
* ami-09d49f099bf4807ba: Pass
* ami-0c6d60295213e8058:  EFS tests and IMDSv2 tests Failed
* ami-02f9c3162bf307a0f: Pass
By submitting this pull request, I confirm …
=> Add back oci-add-hooks to neuron recipe (AL2INF only)

scripts/install-docker.sh
Reverting the change to disable userland proxy
=> userland-proxy should be enabled by default

al2022.pkr.hcl, al2022arm.pkr.hcl, al2022neu.pkr.hcl, scripts/al2022/user-data.sh
This was added to workaround a bug in the packer amazon plugin: https://github.com/hashicorp/packer-plugin-amazon/issues/172
The bug was fixed in plugin version 1.0.8, and we have now internally migrated to plugin 1.1.5, so we no longer need the workaround.
External users can run `packer init -upgrade` to upgrade their packer plugin versions if they still see this bug locally.
AL2022 builds was tested locally and in internal build pipelines 
enhancement - Remove AL2022 user-data ssh access workaround
=> Remove AL2022 user-data ssh access workaround

al1.pkr.hcl, al2.pkr.hcl, al2022.pkr.hcl, al2022arm.pkr.hcl, al2022neu.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl, al2kernel5dot10.pkr.hcl, al2kernel5dot10arm.pkr.hcl, variables.pkr.hcl
Currently we hard-code instance type to use for building AMIs. This PR makes use of `spot_instance_types` for building AMIs to allow multiple candidate instance types. The value is read from variable which means we will be able to dynamically configure the instance type(s) to be used. 
* Create 5 new variables `[general_purpose|gpu|arm|inf|neu]_instance_types`, representing the 5 AMI platform/categories that we currently support. Each variable has a default value, which contains the instance type that we have been using so far.
* Updated all recipes. We replace `instance_type` with `spot_instance_types`. Each recipe's `spot_instance_types` reference their corresponding `<platform>_instance_types` variable. We use `spot_price = "auto"` in order to not set price limits. 
* We are using …
=> Use spot_instance_types for building AMIs

al1.pkr.hcl, al2.pkr.hcl, al2022.pkr.hcl, al2022arm.pkr.hcl, al2022neu.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl, al2kernel5dot10.pkr.hcl, al2kernel5dot10arm.pkr.hcl
In PR #104, we added support for using spot instances to build AMIs. 
Since spot instance types are not supported in all regions where we build AMIs, we'll just use regular EC2 instances until support is available.
Note that we'd still continue to dynamically retrieve candidate instance types during build time.
1. `spot_instance_types` -> `instance_type` and removed `spot_price` from all packer recipes.
2. The {family}_instance types variable is a list which we override during build time, by querying available instance types in that particular region. Since this list is already random or in no particular order, we'll use the first element in the list. This also works in case we want to use the default type.
Tested the changes by building an AMI in …
=> do not use spot instances to build AMIs

scripts/cleanup.sh
As [stated in the Amazon Linux 2023 User Guide](https://docs.aws.amazon.com/linux/al2023/ug/package-management.html):
> In Amazon Linux 2023 (AL2023), the default software package management tool is DNF. DNF is the successor to YUM, the package management tool in Amazon Linux 2.
> In AL2023 the `yum` command is still available, but as a pointer to the `dnf` command. 
There is a bug where our cleanup script is missing steps in cleaning up DNF files, including DNF history (see example in Testing section below). This pull request updates our cleanup script to handle cleanup of DNF files.
Update cleanup script with commands to clean up DNF files in the same way we do for YUM files.
Also add comment for context regarding YUM commands being redirected to DNF for AL2023.
**Before this pull …
=> Handle dnf cleanup for AL2023 AMIs

generate-release-notes.sh
Add a script `generate-release-notes.sh` for generating release notes. 
The script takes two required parameters - AL2 GPU NVIDIA driver version and AL2 GPU CUDA driver version, and one optional parameter - AL1 containerd version. AL1 containerd version should only be provided when there is an AL1 release. The script will include AL1 in the generated release notes if AL1 containerd version is provided.
```
Usage:
./generate-release-notes.sh AL2_GPU_NVIDIA_VERSION AL2_GPU_CUDA_VERSION [AL1_CONTAINERD_VERSION]
AL1_CONTAINERD_VERSION should not be provided if there is no AL1 AMI release
Example:
./generate-release-notes.sh 470.182.03 11.4 1.4.13 # AL1 release included
./generate-release-notes.sh 470.182.03 11.4        # No AL1 release
```
The script - 
* requires AL2 GPU NVIDIA driver …
=> Add a script to generate release notes

scripts/install-exec-dependencies.sh, variables.pkr.hcl
- Update the execute-command-agent ssm static binary to version `3.2.1478.0`
- Update the shasum for each.
Validated previous `3.1.1732.0` shasums using the `sha256sum` linux utility.  Downloaded each of the new tar files and generated the shas using the same utility.
Validated the generated shas for both the previous and the current versions multiple times for each arch.
Update execute-command-agent to 3.2.1478.0.
=> update exec ssm version

scripts/enable-ecs-agent-gpu-support.sh
This PR is to enable NVIDIA Persistence Daemon by default
Added `sudo systemctl enable nvidia-persistenced` to `scripts/enable-ecs-agent-gpu-support.sh`
- REGION=us-west-2 make al2gpu
- Launch instance with test AMI and verify nvidia-persistenced.service is enabled, active (running)
```
systemctl status nvidia-persistenced
● nvidia-persistenced.service - NVIDIA Persistence Daemon
Loaded: loaded (/usr/lib/systemd/system/nvidia-persistenced.service; enabled; vendor preset: disabled)
Active: active (running) since Tue 2023-09-26 04:07:02 UTC; 1min 7s ago
Main PID: 4705 (nvidia-persiste)
Tasks: 1
Memory: 28.1M
CGroup: /system.slice/nvidia-persistenced.service
└─4705 /usr/bin/nvidia-persistenced --verbose
```
- Run functional set suite against the AMIs created and verify exec tests succeed
New …
=> Enable NVIDIA Persistence Daemon by default

variables.pkr.hcl
Upgrade Amazon SSM Agent version to[ 3.2.1630.0](https://github.com/aws/amazon-ssm-agent/releases/tag/3.2.1630.0), which is the latest stable version, to address CVE listed as follows.
1. [Important] https://alas.aws.amazon.com/ALAS-2023-1825.html
2. [Important] https://alas.aws.amazon.com/AL2/ALAS-2023-2238.html
3. [Important] https://alas.aws.amazon.com/AL2023/ALAS-2023-373.html
4. [Important] https://alas.aws.amazon.com/AL2023/ALAS-2023-339.html
Update `exec_ssm_version` in variables.pkr.hcl.
1. Built Alpha ECS optimized AL2, AL2 ARM, AL2023, AL2023 ARM, and AL1 AMIs with following parameters for testing
```
ami_version          = "29999999"
ecs_agent_version    = "1.76.0"
ecs_init_rev         = "1"
docker_version       = "20.10.23"
docker_version_al2023 = "20.10.23"
containerd_version …
```
=> Update SSM Agent version to 3.2.1630.0 for ECS exec

scripts/enable-ecs-agent-inferentia-support.sh
This PR removes a typo `use` from the enable-ecs-agent-inferentia-support.sh.
P.S. The associated PR is https://github.com/aws/amazon-ecs-ami/pull/149.
Remove a typo `use` from enable-ecs-agent-inferentia-support.sh.
1. Build a new AL2023 NEU with the updated script, and confirm Neuron devices and with Neuron tools tests both pass.
```
==> amazon-ebs.al2023neu: + [[ al2023neu == \a\l\2\i\n\f ]]
==> amazon-ebs.al2023neu: + sudo yum install -y aws-neuronx-tools
amazon-ebs.al2023neu: Last metadata expiration check: 0:02:18 ago on Tue Oct 10 17:02:47 2023.
amazon-ebs.al2023neu: Dependencies resolved.
amazon-ebs.al2023neu: ================================================================================
amazon-ebs.al2023neu:  Package                  Architecture  Version             Repository …
```
=> Fix a typo in the enable inf support script

Makefile, README.md, al2.pkr.hcl, al2keplergpu.pkr.hcl, scripts/enable-ecs-agent-gpu-support.sh
With the release of `20230912` AMI, default Nvidia and Cuda drivers were updated in AL repos. These further later added support for P5 instances but lost support for P2 instances (Kepler architecture), for which Nvidia 470 is the latest supported driver.
This PR adds a new `al2keplergpu` build recipe to support building AL2 ECS Optimized GPU AMIs with this package for instances with Kepler arch GPUs (such as P2 type). This recipe is NOT a new supported ECS platform, no new AMI types are published for this type. Rather it is a build recipe for anyone to build their own ECS AMIs for Kepler instances with GPUs on Kepler architecture.
This will enable customers to create their own GPU supported AMIs for Kepler based GPU instances (such as P2.xlarge) by
* Setting the required Agent and source …
=> add al2keplergpu build recipe to build gpu amis for kepler arch

al2gpu.pkr.hcl, generate-release-vars.sh, variables.pkr.hcl
Temporarily override base AMI for AL2 GPU due to a known al2 kernel and EFA/Nvidia incompatibility
Add a variable and change al2gpu recipe to use a pinned al2 base AMI.
Ran `REGION=us-west-2 make al2gpu` and verified a pinned base AMI is used (ami-0bac1825e471f5042)
=> Temporarily override GPU base AMI

.github/workflows/pushcodecommit.yml, al2gpu.pkr.hcl, generate-release-vars.sh, variables.pkr.hcl
This pull request includes Github workflow additions. The added Github Action is intended to mirror the ecs-ami repository to an internal CodeCommit repository. 
The action was run a few times in personal forked repository for testing purposes and verified to work. 
- File changes were seen reflected in the codecommit repository.
- File deletions, file additions were reflected in the codecommit.
- Only changes from shinkansen branch were updated to the codecommit shinkansen branch.
- All of commit history is seen on mirrored branch up to the present. 
Added the new action file under .github/workflows/ and populated with workflow steps. 
=> Add action to push to codecommit mirror repository

check-update-security.sh
This change adds a script to check for a security update based on a given ami ID. 
The shell script launches an EC2 instance with the specified AMI ID and checks for updates using SSM run command. The response of the command is relayed so the caller of this script is notified whether an update is necessary for the specified AMI. 
Tested in developer environment. 
IAM_INSTANCE_ROLE environment variable was setup to allow EC2 to launch SSM Agent
The below amis were tested by hardcoding, indicating updates by returning true.
Test: ami_id="ami-0df7393b3a1210727" #OLD AL1 AMI
Result: true
Test: ami_id="ami-04e6179c63d17513d" # OLD AL2 AMI
Result: true
Test: ami_id="ami-0c972b8adbd52bea0" # OLD AL2_ARM AMI
Result: true
Test: ami_id="ami-000e1cfd42f014991" # OLD Al2023 AMI
Result: true
Test: …
=> Add script to check for security update of given ami

scripts/cleanup.sh
This PR makes a change to the cleanup script. In this script, while cleaning up SSM log files, we first shred the files and then delete the entire directory. We do this as per https://docs.aws.amazon.com/imagebuilder/latest/userguide/security-best-practices.html#post-build-cleanup.
Building an AMI using `make al2023` based off the latest main branch fails with the following error:
```
amazon-ebs.al2023: Deleting files within /var/log/amazon/ssm/*
==> amazon-ebs.al2023: + sudo find /var/log/amazon/ssm -type f -exec shred -zuf '{}' ';'
==> amazon-ebs.al2023: shred: /var/log/amazon/ssm/patch-baseline-operations/botocore/data/apigateway/2015-07-09/paginators-1.json: failed to remove: No such file or directory
==> amazon-ebs.al2023: find: …
```
=> ssm logs cleanup: skip shredding files since we're deleting the entire directory

generate-release-vars.sh
These changes to generate-release-vars.sh reflect the changes done in [this commit](https://github.com/aws/amazon-ecs-ami/commit/35af16d95614f3a1937e73b634cba413f509a147). The script will now update the specific file instead of the previously existing general file for base AMI versions. The script will have to be run for each variant of AMI: AL1, AL2, and AL2023. This change is for internal reasons and allows for more flexibility for desired changes. 
Instead the general all AMIs file, a switch case, taking the AMI type, will determine which file to update, and will only run the commands and API calls necessary to get the information for updating that specific file. 
The agent and ecs-init versions are not needed based on the files' structures as of now. A future change, based on the …
=> Change generate-release-vars.sh to update specific release files

.github/workflows/generateconfig.yml, generate-release-vars.sh, release-al1.auto.pkrvars.hcl, scripts/check-update-security.sh, scripts/check-update.sh
Add generate config github action. The action checks runs ./generate-release-vars.sh, sees if there are any dependency updates, and pushes to the repository in the case of a release needing to be kicked off. If no dependency updates exist, it will fall back to checking security updates by launching an ec2 instance with the AMIs and checking for critical updates.
Also includes a couple modifications to the check update security script to make it more resilient to API errors, that occurred in a couple rare test scenarios. 
The action was split into steps of a github action, and runs on workflow dispatch as of now. 
A testing document was made to check all important test scenarios. 
New tests cover the changes: yes
Add GenerateConfig github action
By submitting this pull request, I confirm …
=> Add generateConfig action, updates to check-update-security and generate-release-vars.sh

scripts/enable-ecs-agent-gpu-support.sh, variables.pkr.hcl
This change builds a .tar file of the open source NVIDIA kernel module in `/var/lib/dkms-archive/nvidia-open`.  It also adds a script to replace the closed source NVIDIA kernel module with this open source NVIDIA kernel module.  This allows AMI users (especially those using P4/P5 instances with EFA) to run a simple command in userdata/cloud-init to replace the kernel module.
This also un-pins the gpu kernel version to pull in the latest updates.
Built AMI using packer `REGION=us-west-2 make al2gpu`.  
Resulting test AMI: ami-028c1796865c0d2ae
I started an instance of this ami with userdata to run the open module installation script:
```
#!/bin/bash
/var/lib/ecs/scripts/install-nvidia-open-kmod.sh
yum versionlock \
cuda-* \
cuda-drivers-* \
cuda-drivers-fabricmanager-* \ …
```
=> Add post-kepler nvidia open kernel module installation steps

al1.pkr.hcl, al2.pkr.hcl
This change makes it so that a packer build of AL1 or AL2 (all flavors) automatically run security updates. 
A step was added into the build for AL1 and AL2 that runs a line of bash to update the security packages. This was not needed for AL2023, because it is version locked, and security updates are only applicable by using a new distribution release. Since a new distribution release is already installed in the recipe for AL2023, we need not have a specific security update step. 
After running make al1, and al2, the images were successfully built, and the additional sudo yum update... bash line was run during the build without errors. 
Addition to build recipe of AL1 and AL2 to update security packages during build. 
By submitting this pull request, I confirm that my contribution is made …
=> Add security update install script in build recipe for al1 and al2

al2gpu.pkr.hcl, generate-release-vars.sh, variables.pkr.hcl
This updates the generate release vars script to use AL2/x86 as the base GPU AMI
Update the script to use `ami_name_al2_x86` as the source_ami_al2_gpu
Revert pinned gpu base AMI.
=> use ami_name_al2_x86 for gpu base ami

scripts/check-update-security.sh, scripts/check-update.sh
In a feature implementation for AMI release, two scripts were added under scripts in the repository that, working together, checked whether any of the AMI types require an update and complete necessary steps to automatically kick off a release. After writing it, it was noticed that AL2023 security updates come with the latest version of AL2023, and therefore it is redundant to check for security updates in a separate script if the version of AL2023 is already detected to have an update. Therefore, the implementation for check-update-security.sh was modified to not include AL2023 as a possible check, and check-update.sh was modified to not run check-update-security.sh with al2023 argument. 
The changes are in scripts/check-update.sh and scripts/check-update-security.sh. The change in …
=> Remove unnecessary security update checks for al2023

generate-release-notes.sh
Refactor generate release notes script (i.e., `generate-release-notes.sh`) to fit with the enhanced release process being worked on in branch `feature/shinkansen`.
**NOTE:** This pull request will be merged into branch `feature/shinkansen`.
- Take in options/flags instead of having set arguments with a specific order for AL2 NVIDIA version, AL2 CUDA version, and AL1 containerd version
- Make AL2 NVIDIA version and AL2 CUDA version options optional, as with the enhanced release process AL2 GPU AMIs may not necessarily be released during every AMI release
- Define new option/flag `--exclude-ami` to specify what AMI variants are excluded in a given release, as with the enhanced release process any given AMI variant may not necessarily be included
- Only generate release notes for AMI …
=> Refactor generate release notes script for enhanced release process

scripts/enable-ecs-agent-gpu-support.sh
After installing dkms and nvidia open modules, remove and cleanup the epel repo.
The reason for this is that the epel repo is a public fedora repo. The URLs of this repo require access to the open internet. Customers using isolated subnets will not have internet access so all package updates and installs will fail when yum tries talking to the epel repo.
Removing it ensures that the AMI by default only points to internal Amazon Linux repos which are accessible in isolated subnets.
al2gpu AMI built, ran /var/lib/ecs/scripts/install-nvidia-open-kmod.sh script
Bugfix: Fix al2gpu AMI package installs and updates when running in isolated subnets
=> al2gpu: Remove epel repo after installing dkms and nvidia open modules

al2.pkr.hcl
Currently, on a freshly booted instance we see following
```
[ec2-user@ip-172-31-95-15 yum.repos.d]$ ls -lh
total 8.0K
-rw-r--r-- 1 root     root     1003 Sep 26 22:32 amzn2-core.repo
-rw-r--r-- 1 ec2-user ec2-user  972 Jan 12 17:58 amzn2-extras.repo
```
The `ec2-user` user and group should not own repo configs. This PR updates owner and owner group to `root`.
On a freshly booted instance with test AMI built with the updated recipe, verified that 
```
[ec2-user@ip-172-31-28-12 yum.repos.d]$ ls -lh
total 8.0K
-rw-r--r-- 1 root root 1003 Sep 26 22:32 amzn2-core.repo
-rw-r--r-- 1 root root  972 Feb  7 18:16 amzn2-extras.repo
```
change amzn2-extras.repo file owner to root
By submitting this pull request, I confirm that my contribution is made under the terms …
=> change amzn2-extras.repo file owner to root

al1.pkr.hcl, al2.pkr.hcl, al2023.pkr.hcl, al2023arm.pkr.hcl, al2023neu.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl, al2keplergpu.pkr.hcl, al2kernel5dot10.pkr.hcl, al2kernel5dot10arm.pkr.hcl, generate-release-vars.sh, release-al1.auto.pkrvars.hcl, release-al2.auto.pkrvars.hcl, release-al2023.auto.pkrvars.hcl, variables.pkr.hcl
This PR decouples ami_version across ami families. This is because we do packer inspect during our AMI builds via `./packer inspect`. This gets the `ami_version` from the last read `release-{al1/al2/al2023}.auto.pkrvars.hcl` file. Hence we need to make the ami_version a unique key across the different release configs.
rename ami_version to ami_version_{al1/al2/al2023}.
Ran ./scripts/check-update.sh to generate the release config files.
bugfix: decouple ami_version across ami families
=> decouple ami_version across ami families

scripts/install-ecs-init.sh
This PR updates the variable name from `INIT_LOCAL_OVERRIDE` to `ECS_INIT_LOCAL_OVERRIDE` in the `install-ecs-init.sh`. (Note: This variable is introduced by the previous PR https://github.com/aws/amazon-ecs-ami/pull/40 to support installing ecs-init rpms from a local source).
Use `ECS_INIT_LOCAL_OVERRIDE` in `install-ecs-init.sh`.
1. Download ecs-init version 1.81.0 rpm to the `additional-packages` folder
2. Build an AL2 AMI with `ecs_init_local_override` set to `ecs-init-1.81.0-1.amzn2.x86_64.rpm`.
3. The AL2 AMI is built successfully, and it passed all e2e functional tests.
An sample packer log: 
```
==> amazon-ebs.al2: + mkdir /tmp/additional-packages
==> amazon-ebs.al2: Uploading additional-packages/ => /tmp/additional-packages
...
==> amazon-ebs.al2: Provisioning with shell script: …
```
=> Fix ECS_INIT_LOCAL_OVERRIDE in install-ecs-init.sh

generate-release-notes.sh
Update generate release notes script to take into account the changes from https://github.com/aws/amazon-ecs-ami/pull/202.
See Summary above.
Tested as part of generating the 20240212 release notes.
Update generate release notes script to factor in decoupled ami_version across ami families
=> Update generate release notes script to factor in decoupled ami_version across ami families

variables.pkr.hcl
This PR updates the containerd versions in `variables.pkr.hcl` for both AL2, and AL2023. This will be picked up in the next ECS AMI release.
Ran the internal qualification process.
enhancement: update containerd version to 1.7.11
=> update containerd version to 1.7.11

.github/CODEOWNERS, .github/workflows/initiaterelease.yml, .github/workflows/manualtrigger.yml, scripts/check-update-security.sh, scripts/check-update.sh
- Changes to Github InitiateReleaseAction to create a PR instead of push directly to the repository.
- Also adds schedule for the action to run on.
- Also adds CODEOWNERS file to prevent non-aws-agent team members from triggering the github action. 
- Use the actions/checkout@v4.
There is no longer a push in the github action to the aws/amazon-ecs-ami repository main branch. It now creates a branch for the release and pushes everything there. Then, if this is successful, it opens a pull request for the release. Instead of pushing to codecommit the latest main branch, it instead pushes the created branch. The reviewer then reviews both the internal and GH open PR at the same time.
The following InitiateRelease was updated in my personal fork: …
=> Make release action PR instead of push directly

scripts/check-update.sh
Fix premature exiting issue regarding InitiateRelease github action. 
Add failure preventing code around "diff" command to prevent a non-zero exit code from being interpreted as a failure. 
Tested previously on personal fork with test action. This file change being separate from the InitiateRelease action caused this change to be missed. 
New tests cover the changes: n/a
N/A
=> Fix diff calculation error out on github action

variables.pkr.hcl
Upgrade Amazon SSM Agent version to[ 3.2.2222.0](https://github.com/aws/amazon-ssm-agent/releases/tag/3.2.2222.0), to address CVE listed below:
1. https://alas.aws.amazon.com/cve/html/CVE-2023-49569.html
Built an Alpha AMI, ran e2e testing and confirmed that all tests pass.
Enhancement: Update exec ssm version to 3.2.2222.0
=> Update exec ssm version to 3.2.2222.0

Makefile, README.md, al2.pkr.hcl, al2kernel5dot10gpu.pkr.hcl, al2kernel5dot10inf.pkr.hcl, scripts/al2/install-kernel5dot10.sh, scripts/al2/reboot-for-kernel-upgrade.sh, scripts/enable-ecs-agent-gpu-support.sh, scripts/enable-ecs-agent-inferentia-support.sh
Add new GPU and INF packer recipes using AL2 kernel 5.10.
- Create `al2kernel5dot10gpu.pkr.hcl` and `al2kernel5dot10inf.pkr.hcl`
- Modify `al2.pkr.hcl` build sources to include `al2kernel5dot10gpu` and `al2kernel5dot10inf`
- Add new targets `al2kernel5dot10gpu` and `al2kernel5dot10inf` to `Makefile` and `README.md`
- Run AL2 install kernel 5.10 script when `AMI_TYPE` starts with "al2kernel5dot10"
- Run enable GPU support script when `AMI_TYPE` starts with "al2" and ends with "gpu"
- Make sure the NVIDIA driver used is compiled with the appropriate GCC version (gcc10) for kernel 5.10 GPU AMI type
- Ref: https://nvidia.custhelp.com/app/answers/detail/a_id/5323/~/known-issue%3A-nvidia-vgpu-software-graphics-driver-installation-fails-on-some 
- Run enable Inferentia support script when …
=> Support AL2 kernel 5.10 GPU and INF

generate-release-notes.sh
Add AL2 GPU Kernel 5.10 and AL2 Neuron (INF) Kernel 5.10 variants of the ECS-Optimized AMI to the generate release notes script.
**IMPORTANT**: The changes in this pull request are dependent on SSM parameters being published for these new variants of the ECS-Optimized AMI. Thus, this pull request will not be merged until ECS Agent team is ready to publish these new AMI variants (and their SSM parameters) for the first time.
Manually temporarily replaced the currently unavailable GPU/INF kernel 5.10 SSM parameters (on L246 and L253) with the GPU/INF (kernel 4.14) SSM parameters. Afterwards, tested generating release notes for `20240305` release using `./generate-release-notes.sh --al2-gpu-nvidia-ver 535.161.07 --al2-gpu-cuda-ver 12.2.2 --al1-containerd-ver …
=> Add AL2 GPU/INF kernel 5.10 AMIs to release notes

al1.pkr.hcl, al2.pkr.hcl, al2023.pkr.hcl, scripts/setup-ecs-config-dir.sh
Set up the ECS config directory at AMI build time if it is not already present.
- Create script `scripts/setup-ecs-config-dir.sh`
- Call this script for all AL AMI families (i.e., AL2023, AL2, AL1) as all can benefit from this change
Build AL2023, AL2, and AL1 AMD64 custom AMIs with these changes and run functional tests against them.
Setup ECS config directory if not present 
=> Setup ECS config directory if not present

al2.pkr.hcl, al2023.pkr.hcl, al2023arm.pkr.hcl, al2023neu.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl, al2keplergpu.pkr.hcl, al2kernel5dot10.pkr.hcl, al2kernel5dot10arm.pkr.hcl, al2kernel5dot10gpu.pkr.hcl, al2kernel5dot10inf.pkr.hcl
This PR adds `include_deprecated=true` to the AMI recipes.
During an AMI build, Packer uses the name of the Amazon Linux source AMI we defined in `release-*.auto.pkvars.hcl`. It uses the most recent AMI that has the given name. In AL1 recipe, we added `included_deprecated=true` since the AL1 base AMIs are deprecated.
This PR adds the same flag to all other recipes, so that whenever the base AMI is deprecated, Packer is still able to find and use it. It doesn't change anything functionally, but is more of a safety net - for example, when Amazon Linux deprecates the AL2 base AMI in the future, ECS AMI builds will not be impacted.
Updated all AMI recipes with `include_deprecated=true` like it is in the [AL1 recipe](https://github.com/aws/amazon-ecs-ami/blob/291de54065ebbda8b6fca594d899ea49afe …
=> Add include_deprecated=true to all recipes

al2.pkr.hcl, files/69-available-updates-begin.sh.amzn2, files/71-available-updates-finish.sh.amzn2, files/90_ecs.cfg.amzn2
By default, ECS-optimized AL2 AMIs install critical and important security updates at launch. This behavior is inherited from AL2.
After June 12, newly released ECS-optimized AL2 AMIs will no longer install security updates at launch.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html#ecs-optimized-AMI-security-changes
This PR disables security updates at launch for ECS-optimized AL2 AMIs and updates the MOTD to notify about the security changes.
The cloud config inherited from AL2 includes the line `repo_upgrade: security`. This causes security updates to be installed at launch.
Override this setting by adding `repo_upgrade: none` to the [ECS-optimized AL2 cloud config](https://github.com/aws/amazon-ecs-ami/blob/main/files/90_ecs.cfg.amzn2). This will …
=> Disable security updates at launch for ECS-optimized AL2 AMIs

CHANGELOG.md
- al2 ami version: 20240611
- enhancement: Disable security updates at launch for ECS-optimized AL2 AMIs [#254](https://github.com/aws/amazon-ecs-ami/pull/254)
=> Update CHANGELOG 20240611

scripts/install-docker.sh
Update to internal release process requires us to not skip the install docker step in this script. 
Remove no longer necessary air-gapped region control flow. 
Will be tested internally. 
Update install-docker script
=> Remove air-gapped region check in install-docker script

.github/workflows/initiaterelease.yml
* Change the cron schedule of github actions to run at 6PM UTC from Mon - Fri instead of running only on Tuesdays at 6PM UTC
* Verified cron expression using https://crontab.guru/#0_18_*_*_1-5
=> Change cron schedule of github actions

scripts/enable-ecs-agent-inferentia-support.sh
This PR adds oci-add-hooks package to the ECS AL2023 Neuron AMI. We install this package on the AL2 (and AL2 Kernel 5.10) INF AMIs today.
- `scripts/enable-ecs-agent-inferentia-support.sh`: Removed the condition that skips installation on anything other than the AL2 (and AL2 Kernel 5.10) INF AMIs. Only the AL2 (and AL2 Kernel 5.10) INF and AL2023 NEU ECS AMI recipes consume this code, so it is safe to remove the condition completely.
- Built a test AMI and ran our agent and AMI functional tests against it. They passed.
- Follow the docker runtime setup for OCI neuron as described in this [AWS neuron tutorial](https://awsdocs-neuron.readthedocs-hosted.com/en/v2.18.2/containers/tutorials/tutorial-oci-hook.html#for-docker-runtime-setup-docker-to-use-oci-neuron-oci-runtime).
- Confirmed that …
=> install oci-add-hooks on al2023 neuron ecs ami

.github/workflows/initiaterelease.yml, .github/workflows/manualtrigger.yml
This PR adds a sleep (30 seconds) in our release GH actions.
We do 2 things in our GH action,
1. Delete a branch from our CodeCommit repository.
2. Recreate the branch by pushing the latest GitHub source code.
We need to wait a bit between the two steps above, so that our internal replication process has enough time to recognize these as 2 distinct steps and prevent a race condition.
N/A
=> adding a sleep in our release GH actions

variables.pkr.hcl
Bump pinned docker version to 25.0.6
docker version was qualified
Enhancement: bump docker to 25.0.6
=> Bump docker version to 25.0.6

variables.pkr.hcl
released in latest AL2023: https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240805.html
Bumps containerd in AL2023 to 1.7.20 to pickup "important" level CVEs.
qualficiation
Enhancement: Bump AL2023 containerd to 1.7.20
=> Bump AL2023 containerd version to 1.7.20

variables.pkr.hcl
Bumps containerd in AL2 to 1.7.20 to pickup "important" level CVEs.
Qualification
Enhancement: Bump AL2 containerd to 1.7.20
=> Bump AL2 containerd version to 1.7.20

variables.pkr.hcl
This PR will add a new package (`iproute`) to be pre-installed within our ECS-Optimized AMIs so that the necessary utility tools will be added/bind mounted to the ECS Agent container.
* Added `iproute-tc` to the list of packages to be installed via `yum` and `dnf` respectively for AL2 and AL2023 AMIs
Regarding the host bind mounts of agent, it seems like we're already including all of the known host directories of where `tc` utility tool will be located in
```
"HostConfig": {
"Binds": [
"/var/run:/var/run",
"/var/log/ecs:/log",
"/var/lib/ecs/data:/data",
"/etc/ecs:/etc/ecs",
"/var/cache/ecs:/var/cache/ecs",
"/sys/fs/cgroup:/sys/fs/cgroup",
"/var/lib/ecs:/var/lib/ecs",
"/var/log/ecs/exec:/log/exec",
"/etc/pki:/etc/pki:ro",
"/run/docker/plugins:/run/docker/plugins:ro", …
```
=> Installing iproute-tc package within AMI recipes

scripts/enable-ecs-agent-inferentia-support.sh
This pr pin the aws-neuronx-dkms package version to 2.17.17.0(the aws-neuron-dkms version from the last INF AMI we released) since the aws-neuronx-dkms.noarch 0:2.18.12.0-dkms package was not successfully installed during AMI build process in AMI release 20240919
Build a test inf ami ami-048bffbac7cedb521 and performed internal testing specific to Inferenetia functionality
```
=> pin the aws-neuronx-dkms package version to 2.17.17.0

scripts/enable-ecs-agent-inferentia-support.sh
Pin the aws-neuronx-dkms package version to 2.17.17.0 only for al2inf, since the newest versions of the Neuron SDK are no longer supporting linux kernel 4.14. For other AMI types with kernel 5.10, install the latest available aws-neuronx-dkms version.
=> only pin the aws-neuronx-dkms package version to 2.17.17.0 for al2inf

variables.pkr.hcl
Update ECS Agent version to 1.88.0
=> Update ECS Agent version to 1.88.0

al1.pkr.hcl, al2.pkr.hcl, al2023.pkr.hcl, al2023arm.pkr.hcl, al2023neu.pkr.hcl, al2arm.pkr.hcl, al2gpu.pkr.hcl, al2inf.pkr.hcl, al2keplergpu.pkr.hcl, al2kernel5dot10.pkr.hcl, al2kernel5dot10arm.pkr.hcl, al2kernel5dot10gpu.pkr.hcl, al2kernel5dot10inf.pkr.hcl, variables.pkr.hcl
Exposes the `ami_ou_arns`, `ami_org_arns`, and `ami_users` variables for configuration.
Resolves https://github.com/aws/amazon-ecs-ami/issues/30
Adds three entries to `variables.tf` for these variables, and pass them through to the underlying `ebs_builder`s 
I have built and deployed both the `al2` and `al2arm` variants. Unfortunately the `make tests` command mentioned doesnt appear to exist but im happy to run any additional tests needed. 
Feature - Support AMI sharing
=> feat: Expose variables to set AMI share permisions

scripts/check-update-security.sh
Add a "Name" tag to EC2 RunInstances API call in `scripts/check-update-security.sh` shell script so that it is easier to identify instances launched via this shell script in the calling AWS account.
Use `--tag-specifications` argument when calling `aws ec2 run-instances` to add "Name" tag to instance that indicates that the instance is used for checking for security updates (and the platform it is checking security updates for).
Manually run the modified command locally using personal AWS account and confirm that the launched instance has the expected "Name" tag.
Tag name for update check's ec2 run-instances call
=> Tag name for update check's ec2 run-instances call

scripts/enable-ecs-agent-gpu-support.sh
This pr update our recipe to pin the version of nvidia-container-toolkit rpms to 1.16.2 so that we don't release version 1.17.1 with known bug https://github.com/NVIDIA/nvidia-container-toolkit/issues/797. 
=> pin the version of nvidia-container-toolkit

scripts/enable-ecs-agent-gpu-support.sh
This PR unpins nvidia-container-toolkit version from 1.16.2. This is because a newer versions (>=1.17.3) are now available in AL repositories which resolve the compatibility issues for legacy container images being reported in https://github.com/NVIDIA/nvidia-container-toolkit/issues/797
unpin nvidia-container-toolkit version
=> unpin nvidia-container-toolkit version

README.md, al2.pkr.hcl, al2023.pkr.hcl, scripts/install-exec-dependencies.sh, variables.pkr.hcl
- Add support for specifying DNS suffixes in AMI builds
- Remove air-gapped region check and early exit
`REGION=us-west-2 make al2`
=> Support ECS Exec at ADC Regions

.github/workflows/initiaterelease.yml, .github/workflows/manualtrigger.yml
Increase the existing sleep time of 30 seconds to 60 seconds in release Github actions. For context, sleep time was first introduced as part of this pull request: https://github.com/aws/amazon-ecs-ami/pull/281. Recent release has shown that the 30 seconds sometimes it still not enough time to prevent the race condition mentioned in that pull request.
N/A
=> Increase sleep time in release Github actions

al1.pkr.hcl, al2.pkr.hcl, al2023.pkr.hcl, scripts/install-exec-dependencies.sh
Recently Exec feature support was extended to Isolated regions as part of https://github.com/aws/amazon-ecs-ami/pull/368. This support is not extended for AL1 AMI builds, as ECS AL1 is EOL and no new support is introduced.
Currently, AL1 AMI builds can fail in isolated region due to failure to download SSM Agent binaries. This is because a proper [DNS suffix](https://github.com/aws/amazon-ecs-ami/blob/ce5990009809ac0306af9610a36dd180258f316c/scripts/install-exec-dependencies.sh#L8) is not passed through to AL1 exec dependencies download script.
This PR skips SSM Agent binaries installation in isolated regions, only for AL1 builds.
Tested successful AL1 and AL2 AMI builds
Skip SSM Agent installation for AL1 in Isolated Regions
By submitting this pull request, I confirm that my contribution …
=> Skip SSM Agent installation for AL1 in Isolated Regions

scripts/enable-ecs-agent-gpu-support-al2023.sh
This PR contains changes to the enable-ecs-agent-gpu-support-al2023.sh file to explicitly install the kernel-devel package that corresponds to 6.1 kernel on AL2023.
In AL2023 version 2023.7.20250331 release, kernel 6.12 was launched. With this launch the kernel-headers packages had a 6.12 version launched as well.
In  enable gpu support for AL23 script https://github.com/aws/amazon-ecs-ami/blob/main/scripts/enable-ecs-agent-gpu-support-al2023.sh#L20, it installs`nvidia-driver` which will install `kernel-headers` as a dependency.
Issue is that with the install of `nvidia-driver` it automatically installs the 6.12 version of `kernel-headers`. For nvidia GPU drivers to work properly, the `kernel-headers ` package have to be of a similar version of the kernel as well.
Added …
=> Explicitly install kernel-devel in enable-ecs-agent-gpu-support-al2023.sh

scripts/al2/install-kernel5dot10.sh, variables.pkr.hcl
This PR will pin the kernel version to 5.10.235* for AL2 5.10 AMIs specifically and downgrading agent version back to 1.93.0.
install-kernel5dot10.sh will now be running the following commands
```
sudo amazon-linux-extras enable kernel-5.10
sudo yum install -y kernel-5.10.235
```
Manually built a AL2 5.10 AMD and ARM AMI
Tested that the kernel version 
```
[ec2-user@ip-172-31-30-34 ~]$ uname -r
5.10.235-227.919.amzn2.aarch64
```
```
[ec2-user@ip-172-31-19-152 ~]$ uname -r
5.10.235-227.919.amzn2.x86_64
```
Bugfix - Pinning kernel version to 5.10.235* and downgrading agent version back to 1.93.0
=> Pinning kernel version to 5.10.235* and downgrading agent version back to 1.93.0

release-al2.auto.pkrvars.hcl, release-al2023.auto.pkrvars.hcl
ECS Optimized AMI Release  20250515
Rolled back AL2023 AMI version to previous `20250505` version.
=> Release 20250515

variables.pkr.hcl
Bump containerd version to 2.0.5, runc version to 1.2.6
Addresses 
- [CVE-2025-22874](https://explore.alas.aws.amazon.com/CVE-2025-22874.html)
- [CVE-2025-4673](https://explore.alas.aws.amazon.com/CVE-2025-4673.html)
Docker qualification was run.
AMI builds were manually run for AL2 and AL2023.
Bugfix: bump containerd version to 2.0.5, runc version to 1.2.6
=> Bump containerd to 2.0.5, runc to 1.2.6

README.md, files/29-ecs-banner-begin.sh.amzn2
Adds a notice regarding EOL of the AL2 ECS-optimized AMI to the README of this repo, and to the MOTD displayed when logging into the AL2 ECS-optimized AMI.
This MOTD message mirrors the same text that the upstream vanilla AL2 AMI displays: 
```
,     #_
~\_  ####_        Amazon Linux 2
~~  \_#####\
~~     \###|       AL2 End of Life is 2026-06-30.
~~       \#/ ___
~~       V~' '->
~~~         /    A newer version of Amazon Linux is available!
~~._.   _/
_/ _/       Amazon Linux 2023, GA and supported until 2028-03-15.
_/m/'           https://aws.amazon.com/linux/amazon-linux-2023/
```
AL2 AMI was built and verified that the MOTD displays correctly
Enhancement: Add AL2 EOL messaging
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Add AL2 EOL notice to README and MOTD

README.md
Update README to default to al2023
NA
=> Change README default instructions from al2 to al2023

variables.pkr.hcl
Fix Packer plugin installation failure in GitHub Actions by pinning Amazon plugin to version 1.3.9 to address HashiCorp's plugin distribution migration.
Updated the Packer plugin configuration in variables.pkr.hcl to use Amazon plugin version 1.3.9, which is the last version available on GitHub releases that's compatible with Packer v1.7.4. This addresses the plugin installation failure caused by HashiCorp moving official plugin distribution from GitHub releases to releases.hashicorp.com starting with version 1.3.10.
__Additional Context:__ This is due to address static check failures in GH due to changes here [](https://discuss.hashicorp.com/t/important-update-official-packer-plugin-distribution-moving-to-releases-hashicorp-com/75972)<https://discuss.hashicorp.com/t/important-update-offic …
=> Set amazon plugin component of Packer to v1.3.9

variables.pkr.hcl
Encountering issues with release due to newer packer version that needs more investigation on how we plan to migrate.
Set version = 1.2.8 to match tooling versions
Spot checked
New tests cover the changes: no 
Pin version to 1.2.8 to unblock release
=> Pin version to 1.2.8 to unblock release

scripts/install-service-connect-appnet.sh
This reverts commit 0f7ac7168c5de4610d04950610476e29dc819f2c. Last week, we temporarily pinned the service connect agent to avoid consuming a version with known issues. That issue has been mitigated, so we are good to remove this temporary pinning.
Confirmed with the service connect agent team.
=> Revert "Temporarily pin ecs-service-connect-agent package to v1.29.12.1"

scripts/enable-ecs-agent-gpu-support-al2023.sh, scripts/enable-ecs-agent-gpu-support.sh
This PR explicitly installs the `nvidia-persistenced` as part of the GPU installation scripts. Our AMI recipes have been pulling this package in as a dependency of one of the other nvidia packages. 
During today's ECS AMI builds, we see an error related to this package. We try to enable nvidia-persistenced as part of our GPU installation/setup scripts: [AL2023](https://github.com/aws/amazon-ecs-ami/blob/29ad55729644ea4334b4cfbfbeff693f56b2f2f4/scripts/enable-ecs-agent-gpu-support-al2023.sh#L44), [AL2](https://github.com/aws/amazon-ecs-ami/blob/29ad55729644ea4334b4cfbfbeff693f56b2f2f4/scripts/enable-ecs-agent-gpu-support.sh#L165)
If this is not marked as a dependency (which seems like it is the case), the `systemctl enable nvidia-persistenced` command fails, because the package was never …
=> Explicitly install nvidia-persistenced

scripts/al2023/gpu/kmod-util
This PR add a utility script called `kmod-util` which serves as a DKMS wrapper to load, remove, archive, build, check module versions of DKMS modules and also check if nvidia-devices are attached to the instance running an ECS AL2023 GPU AMI.
Adds a new bash utility script kmod-util that wraps DKMS operations for kernel module management. The script provides commands to load, remove, archive, and build kernel modules with file locking to prevent concurrent operations. It includes NVIDIA GPU detection and stores module archives in /var/lib/dkms-archive for later use.
Built a custom test AMI and verified that `kmod-util` works as expected
New tests cover the changes:  Yes, tests implemented internally
Add kmod-util script for AL2023 GPU driver kernel-module management
By submitting this …
=> Add kmod-util script for AL2023 GPU driver kernel-module management

scripts/al2023/gpu/nvidia-kmod-load.service, scripts/al2023/gpu/nvidia-kmod-load.sh
This PR introduces a new systemd service `nvidia-kmod-load` and a corresponding script that the service will execute at instance launch that will help instance specific kernel modules to be loaded.
Introduces a new systemd oneshot service called `nvidia-kmod-load`. This service will run on instance launch and will execute the `nvidia-kmod-load.sh` script.
The `nvidia-kmod-load.sh` script will check for the sub device ID of the GPU device attached to the instance and will load the necessary kernel modules required for GPU functionality for that specific instance type. 
Built a custom AMI and verified if the appropriate kernel modules are loaded for each instance type.
On `p3 instances`, proprietary kmods are loaded
```
sh-5.2$ dkms status
nvidia-proprietary/570.172.08, …
```
=> Add NVIDIA kernel module loading service for AL2023 GPU AMIs

variables.pkr.hcl
This PR will bump up the amazon-ssm-agent version to 3.3.3050.0 which includes a fix for [CVE-2025-22871](https://explore.alas.aws.amazon.com/CVE-2025-22871.html) and [CVE-2025-22872](https://explore.alas.aws.amazon.com/CVE-2025-22872.html)
Built alpha AMIs on different platforms and ran our functional tests against them. 
New tests cover the changes: Not applicable
Enhancement - Update amazon-ssm-agent version for exec to 3.3.3050.0
=> Update amazon-ssm-agent version for exec to 3.3.3050.0
