CHANGELOG.md, release.auto.pkrvars.hcl
Changes for 20211120 release.
This release is related to CVE-2021-41190
New packages required in repo:
```
AL2 containerd-1.4.6-7.amzn2
AL2 docker-20.10.7-5.amzn2
AL1 containerd-1.4.6-7.11.amzn1
AL1 docker-20.10.7-5.76.amzn1
```
=> Release 20211120

CHANGELOG.md, release.auto.pkrvars.hcl
=> Revert "Release 20211120"

scripts/cleanup.sh
These changes are made to reflect the AWS image builder security best
practices documented here:
https://docs.aws.amazon.com/imagebuilder/latest/userguide/security-best-practices.html
There were a few files that were not deleted in the script above, so at
the end of the new cleanup script we will continue deleting those with
'rm' and will engage with AWS teams about updating the image builder
script to include those files.
Our script also does not allow configuration of each individual deletion
stage. This is not needed for the OSS ami recipes since users could just
customize this script to their liking if they are creating a custom AMI.
tested using internal functional test framework
Enhancement - changed AMI build cleanup script to be in-line with [ec2 …
=> Cleanup script enhancements

.github/workflows/gitsecrets.yml
[Git secret](https://github.com/awslabs/git-secrets) is a tool scanning commits/commit messages for possible leaks of secret into github.
This pull request add a new github workflow to check the code push and prs. Since git secret is usually installed in dev environment and checking commits when run `git commit`, the way this workflow works is 1) install git secret on worker 2) scan existing code base (instead of individual commits) based on previous clean record to detect problem in the new code changes
Tested with amazon-ecs-agent and amazon-ecs-init personal fork
This contains exactly same change for workflow as https://github.com/aws/amazon-ecs-agent/pull/3104.
Test done for https://github.com/aws/amazon-ecs-agent/pull/3104 : 
Tested failed workflow: …
=> Add git secrets workflow

scripts/install-exec-dependencies.sh, variables.pkr.hcl
Updating the SSM Agent version to 3.1.804.0 as part of customer request.
MACIS tests were successful for all the AMI flavors.
=> Update the SSM Agent version to 3.1.804.0

release.auto.pkrvars.hcl, scripts/al2022/install-workarounds.sh, variables.pkr.hcl
couple of small variable fixups, and update to latest AL2022 release (20220202)
=> recipe fixups

scripts/cleanup.sh
This cleans up the /var/log/messages entries that were created during snapshotting.
This simply just adds the /var/log/messages to the list of log files to be cleaned
Tested that the instance launched with new AMI only has logs in /var/log/messages from the time the instance was launched.
Enhancement: Cleanup /var/log/messages
=> Cleanup /var/log/messges for ECS AMI

CHANGELOG.md, release.auto.pkrvars.hcl
Release 20220520
Use xmllint to get the latest al2022 release and update Docker version #55 
=> Release 20220520

CHANGELOG.md, release.auto.pkrvars.hcl
=> Release 20220607

scripts/install-ecs-init.sh, variables.pkr.hcl
This updates the Docker and Containerd package versions to the latest available.
Updates made to the variables directly
AMI build test successful.
Update AL2022 Docker and Containerd versions
=> Update Docker and Containerd versions

scripts/enable-ecs-agent-inferentia-support.sh
AWS Neuron team recently release the V2 release of neuron. This PR updates our build script to install latest neuron packages and remove some steps that are no longer required.
Built an AMI with updated inferentia script. Run functional test suits using this AMI and passed.
New tests cover the changes:  n/a
Update Neuron build script to use Neuron V2
=> update to use neuron v2

scripts/enable-ecs-agent-inferentia-support.sh
Add back neuron tools to prevent breaking changes. 
There is a new `aws-neuronx-tools` package to replace `aws-neuron-tools` package, however it is not built for AL2 yet.
=> add back neuron tools to prevent breaking changes

CHANGELOG.md, release.auto.pkrvars.hcl
Release 20221213
- ecs version: 1.67.2-1
=> Release 20221213

CHANGELOG.md, release.auto.pkrvars.hcl
Release 20230109
ECS Agent version 1.68.0.
=> Release 20230109

CHANGELOG.md, release.auto.pkrvars.hcl
```
- ecs version: 1.68.1-1
- distribution al2022 release: 2022.0.20230118
```
=> Release 20230127

al2gpu.pkr.hcl, generate-release-vars.sh, variables.pkr.hcl
Pull request to get a main commit into the feature/shinkansen properly since a future commit was added into the previous pull request and now seems to be separate.
=> Temporarily override GPU base AMI (#161)

.github/workflows/initiaterelease.yml, .github/workflows/manualtrigger.yml
Update branch to `main` (instead of feature branch `feature/shinkansen`) in InitiateRelease and ManualPushToCodeCommit Github actions.
See Summary above.
Being tested as part of the first iteration of the enhanced ECS-Optimized AMI release process.
Update branch to main in InitiateRelease and ManualPushToCodeCommit Github actions
=> Update branch to main in InitiateRelease and ManualPushToCodeCommit Github actions

CHANGELOG.md
Update CHANGELOG 20240212
See Summary above.
Update CHANGELOG 20240212
=> Update CHANGELOG 20240212

.github/workflows/initiaterelease.yml, .github/workflows/manualtrigger.yml
Adds metric publishing to keep track of Github Action status for Enhanced ECS Optimized AMI Release. 
A new job is added under the github actions that checks the result of the previous jobs. Based on their result, the appropriate metric is published. 
Tested on hozkaya2000/amazon-ecs-ami fork, metrics were published and manually verified. 
Example workflows: 
ManualTrigger Run: 
https://github.com/hozkaya2000/amazon-ecs-ami/actions/runs/7891946076
InitiateRelease No Release Scenario: 
https://github.com/hozkaya2000/amazon-ecs-ami/actions/runs/7891592873/job/21536259029
InitiateRelease Failure Scenario:
https://github.com/hozkaya2000/amazon-ecs-ami/actions/runs/7891380634/job/21535645058
New tests cover the changes: n/a
ECS Optimized AMI Release Github Action -- Metrics Addition
By …
=> Add metrics to release actions

variables.pkr.hcl
Update ECS Agent version to 1.82.0
=> Update ECS Agent version to 1.82.0

variables.pkr.hcl
Update Amazon SSM Agent version to[ 3.2.2303.0](https://github.com/aws/amazon-ssm-agent/releases/tag/3.2.2303.0) to address CVEs listed below:
1. https://alas.aws.amazon.com/ALAS-2024-1920.html
1. https://alas.aws.amazon.com/ALAS-2023-1866.html
1. https://alas.aws.amazon.com/ALAS-2023-1825.html
1. https://alas.aws.amazon.com/AL2/ALAS-2024-2458.html
1. https://alas.aws.amazon.com/AL2/ALAS-2023-2303.html
1. https://alas.aws.amazon.com/AL2/ALAS-2023-2238.html
1. https://alas.aws.amazon.com/AL2/ALAS-2022-1807.html
1. https://alas.aws.amazon.com/AL2/ALAS-2024-2458.html
1. https://alas.aws.amazon.com/AL2023/ALAS-2024-526.html
1. https://alas.aws.amazon.com/AL2023/ALAS-2023-388.html
1. https://alas.aws.amazon.com/AL2023/ALAS-2023-373.html
1. https://alas.aws.amazon.com/AL2023/ALAS-2023-339.html …
=> Update SSM Agent version to 3.2.2303.0 for ECS exec

variables.pkr.hcl
Update ECS Agent version to 1.82.1
=> Update ECS Agent version to 1.82.1

variables.pkr.hcl
Update AL2023 Docker version to 25.0.3.
Qualification of new Docker version has been completed.
Update AL2023 Docker version to 25.0.3
=> Update AL2023 Docker version to 25.0.3

variables.pkr.hcl
Update ECS Agent version to 1.82.2
=> Update ECS Agent version to 1.82.2

CHANGELOG.md
- al2 ami version: 20240610
- al2023 ami version: 20240610
- source al2023 ami: al2023-ami-minimal-2023.4.20240611.0-kernel-6.1-x86_64
- source al2023 arm ami: al2023-ami-minimal-2023.4.20240611.0-kernel-6.1-arm64
- distribution al2023 release: 2023.4.20240611
=> Update CHANGELOG 20240610

release-al2.auto.pkrvars.hcl
ECS Optimized AMI Release 20240611
=> Release 20240611

variables.pkr.hcl
Update ECS Agent version to 1.84.0
=> Update ECS Agent version to 1.84.0

variables.pkr.hcl
Update AL2 Docker version to 25.0.3
Qualification of new Docker version has been completed.
Update AL2 Docker version to 25.0.3
=> Update AL2 Docker version to 25.0.3

variables.pkr.hcl
=> Update ECS Agent version to 1.85.0

variables.pkr.hcl
=> Update ECS Agent version to 1.85.1

variables.pkr.hcl
Update ECS Agent version to 1.85.2
=> Update ECS Agent version to 1.85.2

variables.pkr.hcl
Update ECS Agent version to 1.85.3
=> Update ECS Agent version to 1.85.3

variables.pkr.hcl
Update ECS Agent version to 1.86.0.
N/A
N/A
Update ECS Agent version to 1.86.0
=> Update ECS Agent version to 1.86.0

variables.pkr.hcl
=> Update ECS Agent version to 1.86.1

variables.pkr.hcl
=> Update ECS Agent version to 1.86.2

variables.pkr.hcl
Update ECS Agent version to 1.86.3 in variables.pkr.hcl
=> Update ECS Agent version to 1.86.3

variables.pkr.hcl
Update runc version in variables.pkr.hcl
Full qualification complete with updated runc version. 
New tests cover the changes: yes
=> Update runc_version and runc_version_al2023

CHANGELOG.md, release-al2.auto.pkrvars.hcl
Release 20240920
al2 ami version: 20240920
- source al2 ami: amzn2-ami-minimal-hvm-2.0.20240916.0-x86_64-ebs
- source al2 arm ami: amzn2-ami-minimal-hvm-2.0.20240916.0-arm64-ebs
- source al2 kernel 5.10 ami: amzn2-ami-minimal-hvm-2.0.20240916.0-x86_64-ebs
- source al2 kernel 5.10 arm ami: amzn2-ami-minimal-hvm-2.0.20240916.0-arm64-ebs
- bug fix: pin the aws-neuronx-dkms package version to 2.17.17.0 only for al2inf [#315](https://github.com/aws/amazon-ecs-ami/pull/315)
=> Release 20240920

release-al2.auto.pkrvars.hcl
ECS Optimized AMI Release 20240925
=> Release 20240925

variables.pkr.hcl
=> Update ECS Agent version to 1.87.0

variables.pkr.hcl
Update `ecs_agent_version`=`1.87.1`
=> Update ECS Agent version to 1.87.1

scripts/enable-ecs-agent-gpu-support.sh
Updates the packages that we use for nvidia-container-runtime-hook. 
To keep up to date on nvidia-container packages, we have switched gpu dependencies 
Full functional and integration test suite was done on all major instance types with the changed packages. 
New tests cover the changes: yes
Update nvidia-container dependency list. 
=> gpu AMI package update

CHANGELOG.md, release-al2.auto.pkrvars.hcl
ECS Optimized AMI Release 20241023
=> Release 20241023

variables.pkr.hcl
This PR will merge the feature/fault-injection feature branch into main.
=> Fault Injection Service feature

variables.pkr.hcl
Update runc version in variables.pkr.hcl
Full qualification complete with updated runc 1.1.14 version.
=> Update runc_version and runc_version_al2023 to 1.1.14

variables.pkr.hcl
Update ECS Agent version to 1.89.1
Update ECS Agent version to 1.89.1
=> Update ECS Agent version to 1.89.1

.github/dependabot.yml, .github/workflows/gitsecrets.yml, .github/workflows/static.yml
Use latest version to leverage on more recent runtime images of actions (mostly NodeJS 16 to 20)
I also propose to use [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) to help sync them up2date (it will open pull requests to be reviewed/merged once a week; can be changed)
=> Update actions workflows

variables.pkr.hcl
=> Update ECS Agent version to 1.89.2

CHANGELOG.md, release-al2.auto.pkrvars.hcl
Enhanced ECS Optimized AMI Release changes
=> Release 20250115

variables.pkr.hcl
Update ECS Agent version to 1.89.3.
N/A
N/A
N/A
=> Update ECS Agent version to 1.89.3

scripts/check-update-security.sh
Disable imdsv1 when launching our "check update" instances
see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-new-instances.html#configure-IMDS-new-instances
Tested by manually running this run-instances command and verifying that the instance runs
NA
=> Change check-update-security disable imdsv1

variables.pkr.hcl
Update ECS Agent version to 1.90.0
Update ECS Agent version to 1.90.0
=> Update ECS Agent version to 1.90.0

variables.pkr.hcl
Bumps containerd version to 1.7.25 in AL2 and AL2023
Qualification
Enhancement: Bump containerd version to 1.7.25 
=> update containerd version to 1.7.25

release-al2.auto.pkrvars.hcl
ECS Optimized AMI Release 20250211
=> Release 20250211

variables.pkr.hcl
Update amazon-ssm-agent version installed for exec feature to `3.3.1802.0`. This version is currently the latest and has fixes mentioned in [ALAS-2025-2739](https://alas.aws.amazon.com/AL2/ALAS-2025-2739.html).
Built AL2 AMD64, AL2 ARM64, AL2023 AMD64, and AL2023 ARM64 ECS-Optimized AMIs and ran exec tests on them. All passed.
Update amazon-ssm-agent version for exec to 3.3.1802.0
=> Update amazon-ssm-agent version for exec to 3.3.1802.0

generate-release-notes.sh
Add AL2023 GPU variants of the ECS-Optimized AMI to the generate release notes script.
**IMPORTANT**: The changes in this pull request are dependent on SSM parameters being published for these new variants of the ECS-Optimized AMI. Thus, this pull request will not be merged until ECS Agent team is ready to publish these new AMI variants (and their SSM parameters) for the first time.
Manually temporarily replaced the currently unavailable AL2023 GPU SSM parameters with AL2 kernel5dot10 gpu parameters to test if release notes generation works.
<details>
<summary>Output for AL2023 GPU</summary>
```
---
* [Amazon Linux 2023 release notes](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html)
* [Amazon Linux 2 release …
```
=> Add AL2023 GPU AMIs to release notes

variables.pkr.hcl
Update ECS Agent version to 1.91.0
Update ECS Agent version to 1.91.0
=> Update ECS Agent version to 1.91.0

variables.pkr.hcl
Update ECS Agent version to 1.91.1
Update ECS Agent version to 1.91.1
=> Update ECS Agent version to 1.91.1

variables.pkr.hcl
Update ECS Agent version to 1.91.2.
Update ECS Agent version to 1.91.2
=> Update ECS Agent version to 1.91.2

variables.pkr.hcl
Bump containerd version to `1.7.27` for both AL2 and AL2023
=> Updating containerd version to 1.7.27

variables.pkr.hcl
This reverts commit 61d5e554e5725344616348789e4b9768d9deb44f.
Revert "Updating containerd version to 1.7.27" as it's not quite ready yet 
=> Revert "Updating containerd version to 1.7.27"

variables.pkr.hcl
=> Update ECS Agent version to 1.92.0

variables.pkr.hcl
This reverts commit b7e8140bd32c1542b3eac9cc1aecd7ec1c4f673a.
Bump up contaienrd version to `1.7.27`
=> Reapply "Updating containerd version to 1.7.27"

variables.pkr.hcl
Update Agent version to 1.93.0.
Update Agent version to 1.93.0.
=> Update ECS Agent version to 1.93.0

variables.pkr.hcl
Update ECS Agent version to 1.93.1
=> Update ECS Agent version to 1.93.1

variables.pkr.hcl
Update ECS Agent version to 1.95.0
Update ECS Agent version to 1.95.0
=> Update ECS Agent version to 1.95.0

scripts/enable-ecs-agent-gpu-support-al2023.sh
This PR makes changes to `enable-ecs-agent-gpu-support-al2023.sh` to add support to P6 instance types.
* Added installation of InfiniBand and NVLSM dependencies (libibumad, infiniband-diags, nvlsm)
* Loaded the ib_umad kernel module for InfiniBand support
* Configured ib_umad to load on boot by adding it to /etc/modules-load.d/
Also made changes to explicitly install `kernel-module-extras` that correspond to the version of the kernel. This is to address https://github.com/aws/amazon-ecs-ami/pull/414#discussion_r2027572187
* Ran a simple ECS GPU task and verified that the task was placed and execution completed as required.
* Ran internal testing suite.
New tests cover the changes:  No
Add support for P6 instances
By submitting this pull request, I confirm that my contribution is made …
=> Add support for P6 instances

README.md
Adds an AL1 EOL notice to the README.
N/A
N/A
AL1 EOL Notice
=> AL1 EOL Notice

variables.pkr.hcl
Update ECS Agent version
Updated variables.pkr.hcl file.
Enhancement: Update ECS Agent version to 1.97.0
=> Update ECS Agent version to 1.97.0
